name: Coverage testcov and doccov
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run testcov
        run: |
          python -m coverage run --omit="VisualizationLib/*,*/*OGS*/*" ./Benchmarks/test_Benchmarks_CI.py
      - name: Get total testcov
        id: total
        run: |
          echo "total=$(python -m coverage report --format=total)" >> $GITHUB_ENV
      - name: Get report testcov
        run: |
          echo "$(python -m coverage report --skip-covered --show-missing)"
      - name: Create testcov Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          # https://gist.github.com/pymanga/b95d546b7e0b224d0c625a2e49f8f3cc
          auth: ${{ secrets.GIST_SECRET }}
          gistID: b95d546b7e0b224d0c625a2e49f8f3cc
          filename: coverage.json
          label: testcov
          message: ${{ env.total }} %
          valColorRange: ${{ env.total }}
          minColorRange: 0
          maxColorRange: 100
      - name: Run docstrcov
        run: |
          echo "doccov=$(python -m interrogate -c docstr_coverage.toml | grep -m2 -Po '\d+\.\d+' | tail -n1)" >> $GITHUB_ENV
      - name: Create docstrcov Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          # https://gist.github.com/pymanga/3ed540b4cee708db3a80270e13126074
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 3ed540b4cee708db3a80270e13126074
          filename: coverage.json
          label: doccov
          message: ${{ env.doccov }} 
          valColorRange: ${{ env.doccov }}
          minColorRange: 0
          maxColorRange: 100
