name: Run Python Tests
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: "Run tests with coverage"
        run: |
          python -m coverage run --omit="VisualizationLib/*,*/*OGS*/*" ./Benchmarks/test_Benchmarks_CI.py
      - name: "Get total"
        id: total
        run: |
          echo "total=$(python -m coverage report --format=total)" >> $GITHUB_ENV
      - name: "Get report"
        run: |
          echo "$(python -m coverage report --skip-covered --show-missing)"
      - name: Create Awesome Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          # https://gist.github.com/pymanga/b95d546b7e0b224d0c625a2e49f8f3cc
          auth: ${{ secrets.GIST_SECRET }}
          gistID: b95d546b7e0b224d0c625a2e49f8f3cc
          filename: coverage.json
          label: Test Coverage
          message: ${{ env.total }} %
          valColorRange: ${{ env.total }}
          minColorRange: 0
          maxColorRange: 100
